# Generates mql5/include/BuildInfo.mqh with the current 7-char git build SHA.
# Run from anywhere; resolves the repo root (dir containing .git).
# Fails with a clear message if not inside a git repository.

$ErrorActionPreference = "Stop"

$repoRoot = (git rev-parse --show-toplevel 2>$null)
if ($LASTEXITCODE -ne 0 -or -not $repoRoot) {
    [Console]::Error.WriteLine("ERROR: not a git repository")
    exit 1
}

$sha = (git rev-parse --short=7 HEAD).Trim()
if ($LASTEXITCODE -ne 0 -or -not $sha -or $sha -notmatch '^[0-9a-f]{7}$') {
    [Console]::Error.WriteLine("ERROR: could not resolve a 7-char git SHA")
    exit 1
}

$includeDir = Join-Path $repoRoot "mql5/include"
New-Item -ItemType Directory -Force -Path $includeDir | Out-Null
$out = Join-Path $includeDir "BuildInfo.mqh"
Set-Content -Path $out -Encoding ascii -Value "// Auto-generated by tools/write_build_info.ps1 - do not edit.`n#define BUILD_SHA `"$sha`"`n"
Write-Output "Wrote $out (#define BUILD_SHA `"$sha`")"
